In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('candidateinfo.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                      7                           7      72000
7          11                      7                           8      80000

In [3]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [4]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [5]:
reg.intercept_

14992.651446693118

In [6]:
reg.predict([[2,8,9]])

array([57935.00537075])

In [7]:
reg.predict([[12,2,2]])

array([58797.46295886])

In [8]:
%matplotlib inline
plt.xlabel('experience','test_score(out of 10)','interview_score(out of 10)')
plt.ylabel('salary($)')
plt.scatter(df.experience,reg.predict(df[['experience','test_score(out of 10)','interview_score(out of 10)']]),color='blue')          

AttributeError: 'str' object has no attribute 'pop'

TypeError: can't multiply sequence by non-int of type 'float'

<Figure size 432x288 with 1 Axes>